/**:
  ros__parameters:
    wheel_radius: 0.28 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.15 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.4 # between front wheel center and rear wheel center
    wheel_tread: 1.8 # between left wheel center and right wheel center
    front_overhang: 1.4 # between front wheel center and vehicle front
    rear_overhang: 1.2 # between rear wheel center and vehicle rear
    left_overhang: 0.15 # between left wheel center and vehicle left
    right_overhang: 0.15 # between right wheel center and vehicle right
    vehicle_height: 2.01
    max_steer_angle: 0.70 # [rad]
